server:
  port: 8765
spring.application.name: gateway

eureka:
  client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
        defaultZone: http://127.0.0.1:8761/eureka/
  instance:
     prefer-ip-address: true
info:
  component:  gateway
eureka.instance.instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
spring.cloud.config.discovery.enabled: true
spring.cloud.config.discovery.serviceId: config-server
endpoints.health.sensitive: true
management.security.enabled: false
#endpoints:
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true
#  health:
#    sensitive: false
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 60000
  MaxTotalHttpConnections: 5000
  MaxHttpConnectionsPerHost: 5000
  ActiveConnectionsLimit: 4000

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000000
#zuul.eureka.default.semaphore.maxSemaphores: 30000
zuul.semaphore.max-semaphores: 30000
zuul.hystrix.command.default.execution.isolation.strategy: SEMAPHORE

zuul.hystrix.command.default.execution.isolation.semaphore.maxConcurrentRequests: 2000
zuul.hystrix.command.default.fallback.isolation.semaphore.maxConcurrentRequests: 2000

zuul:
  host:
    max-per-route-connections: 1000
    max-total-connections: 1000
  sensitiveHeaders: ""
  ignoredServices: "*"
  prefix: /api
  routes:
    USER-SERVICE: /user/**
    AUTH-SERVER: /auth/**
    TEST:  #TEST
       path: /test/**
       serviceId: http://127.0.0.1:8000/api/test

spring:
  redis:
    database: 0
    host: 127.0.0.1
    password:
    pool.max-active: 10
    pool.max-idle: 8
    pool.max-wait: -1
    pool.min-idle: 0
    port: 6379
    timeout: 1000
  zipkin:   #监控开关
    enabled: false
    base-url: http://localhost:9411   #zipkin server地址
  sleuth:
    enabled: false
    sampler:
      percentage: 1  #采样率
